//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是由工具生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace A5
{

    public partial class TryIt
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblUsername;

        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        protected global::System.Web.UI.WebControls.Label lblPassword;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.Label lblRString;

        protected global::System.Web.UI.WebControls.TextBox txtRString;

        protected global::System.Web.UI.WebControls.Button btnNewString;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.Button btnLogout;

        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblWelcome;
        protected global::System.Web.UI.WebControls.TextBox txtZipCode;

        protected global::System.Web.UI.WebControls.Label lblWeatherForecast;
    }
}

